### ISSUE TITLE
Missing file location settings for color.less

### ISSUE THREAD

**Issue by gwmaster** [mzohaibqc/antd-theme-webpack-plugin#10]
hi fantastic plugin!!!!
i build my Multi Project Starter framework for build multiple projects that share same code and basic webpack configuration.
[multiprojectstarter](https://bitbucket.org/gwmaster_gwm/multiprojectstarter/src/master/)
and cant find way tell to antd-theme-webpack-plugin put  color.less file not to root else to specific folder location and i have .
to /dist/starterProject/color.less

**Comment by mzohaibqc** [comment]
@gwmaster you can use `publicPath` key to define relative path. Simply add `publicPath: "."` that will make it relative path "./color.less" instead of default "/color.less".
I hope that will help. Go through closed issues and you will find similar issues and their solution.

**Comment by gwmaster** [comment]
ty    On Wednesday, August 15, 2018, 4:35:11 AM GMT+3, Zohaib Ijaz <notifications@github.com> wrote:  
 
 
@gwmaster you can use publicPath key to define relative path. Simply add publicPath: "." that will make it relative path "./color.less" instead of default "/color.less".
I hope that will help. Go through closed issues and you will find similar issues and their solution.

**Comment by mzohaibqc** [comment]
Add `publicPath: '/starterProject'` in plugin options/config.

**Comment by gwmaster** [comment]
i set  publicPath: '.' and change all to relative now all work perfect colors changing . the problem that i try now to understand its why this not change the other params like size . its work https://github.com/less/less.js/issues/1488 but no in my project

**Comment by gwmaster** [comment]
where the limit as i see the less.js do support change other params
is there source code of extension to extend it and make other support

**Comment by gwmaster** [comment]
https://github.com/less/less.js/issues/1488

**Comment by mzohaibqc** [comment]
@gwmaster This plugin only allows to change color specific css styles. You can update any variable with less.js but you have to write your own code/logic to do this. 
Again, this plugin is just about colors

![image](https://user-images.githubusercontent.com/13637803/44232219-ce7b2a00-a1b9-11e8-8415-44cb020ea697.png)
