### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\antd\lib\style\themes\@{root-entry-name}.less'

### ISSUE THREAD

**Issue by iaminnasr** [mzohaibqc/antd-theme-webpack-plugin#106]
**Describe the bug**
Hi!
I used this package and it worked fine as long as update ant design to 4.17.1 and I encountered an this error 
can you help me please thanks

**Show your code**
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\antd\lib\style\themes\@{root-entry-name}.less'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at buildContents (C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\buildcontents.js:32:27)
    at buildContents (C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\buildcontents.js:35:17)
    at buildContents (C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\buildcontents.js:35:17)
    at buildContents (C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\buildcontents.js:35:17)
    at buildContents (C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\buildcontents.js:35:17)
    at C:\Users\amin\Documents\GitHub\tagrani-front-end\node_modules\less-bundle-promise\lib\compressor.js:49:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {        
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\amin\\Documents\\GitHub\\tagrani-front-end\\node_modules\\antd\\lib\\style\\themes\\@{root-entry-name}.less'
}

**Comment by popmanhe** [comment]
I have the same issue.
looks like less-bundle-promise don't replace variable in the filename.

Probably need to use another library to bundle less files.

**Comment by rafaelncarvalho** [comment]
Use the latest antd-theme-generator

The fix: [antd-theme-generator#100](https://github.com/mzohaibqc/antd-theme-generator/issues/100#event-5835397152)

**Comment by popmanhe** [comment]
Thanks.

Hope author releases 1.2.12 soon and updates the packages.json here and releases a new version to npm as well.

**Comment by rafaelncarvalho** [comment]
@popmanhe don't need the update. This project use any version of antd-theme-generator above 1.2.8. Just remove and re-add it will get the latest version

**Comment by mzohaibqc** [comment]
Thank you so much @popmanhe for helping others with regard to this issue. 
Being a Dad of a new born is not easy so I don't have much time to fix every issue. Last weekend, I spent sometime and fixed the bug in antd-theme-generator but couldn't updated this package. 
It will be great if someone can update this and test in one example project under examples folder. I will merge PR and publish new version on npm.

**Comment by popmanhe** [comment]
It was @rafaelncarvalho who was helping others. 

I'd like to help too.  as @rafaelncarvalho said, there is nothing we should be doing. As soon as antd-theme-generator is updated by npm i, everything works. Unless I missed something.

**Comment by mzohaibqc** [comment]
Thanks @rafaelncarvalho
@popmanhe you can just install latest version of antd-theme-generator after installing antd-theme-webpack-plugin
