### ISSUE TITLE
antd theme 

### ISSUE THREAD

**Issue by suifeng-eng** [mzohaibqc/antd-theme-webpack-plugin#108]
按照你的这个插件确实可以改变antd 的框架的组件主题色，请问自己定义的样式 背景颜色怎么跟随主题变化呢

**Comment by mzohaibqc** [comment]
Just use a unique background color variable for your background style as
well as in variable file which you need to provide to this plugin. For
more, read README file

**Comment by suifeng-eng** [comment]
好的 已经解决了，谢谢！
