### ISSUE TITLE
Upgrade antd-theme-generator

### ISSUE THREAD

**Issue by chenshuai2144** [mzohaibqc/antd-theme-webpack-plugin#12]
The antd-theme-generator package is written to death and needs to be upgraded to use the new features.
```
 "antd-theme-generator": "1.0.6",
```

**Comment by mzohaibqc** [comment]
Latest version has v1.1.3 has been deployed and contains two new features
1. Using Cache to improve performance
2. Added support to handle imports starting with `~` that's supported by webpack so now imports like `@import '~antd/lib.....'` will work

**Comment by chenshuai2144** [comment]
package.json id 1.1.6!

**Comment by mzohaibqc** [comment]
Oh.. I got your point... I'll update this package today..

**Comment by mzohaibqc** [comment]
@chenshuai2144 Updated antd-theme-generator dependency veriosn
Now lates version is `antd-theme-webpack-plugin@1.1.8`

![image](https://user-images.githubusercontent.com/13637803/44799105-979b1000-abcc-11e8-88bc-ae85e2746144.png)
