### ISSUE TITLE
Is there a way to use it in umi project?

### ISSUE THREAD

**Issue by dreamerblue** [mzohaibqc/antd-theme-webpack-plugin#17]
[umi](https://github.com/umijs/umi) is a powerful framework for antd and dva users.

Now I'm using umi to develop and I don’t know is there a way to use the antd-theme-webpack-plugin in umi? The ability to modify less var dynamically is really important for our projects.

**Comment by mzohaibqc** [comment]
@dreamerblue You can use core script instead of webpack plugin. Use this https://github.com/mzohaibqc/antd-theme-generator. Have a look at examples.
Here is sample code to generate `color.less` https://github.com/mzohaibqc/antd-theme-generator/blob/master/examples/create-react-app/color.js
