### ISSUE TITLE
styles are overriding many times.

### ISSUE THREAD

**Issue by nunoblue** [mzohaibqc/antd-theme-webpack-plugin#18]
Thanks for your project.

My issue is all variable items are repeated 3 times in color.less.

![ant-theme-problem](https://user-images.githubusercontent.com/1445571/51239245-3083c980-19bc-11e9-8f8d-58f7170f1176.png)

**Comment by mzohaibqc** [comment]
@nunoblue I'll look into this soon

**Comment by mzohaibqc** [comment]
@nunoblue This is not due to this plugin. This is due to because you have imported some styles multiple times. I think you are manually importing Ant design styles in components' files. If that's the case, you need to fix your code otherwise create a repo and reproduce that so that I can review

**Comment by nunoblue** [comment]
Ant Design styles imported in mainLessFile like below.
`@import '~antd/dist/antd.less';`
And some styles are override in other files.
I'll fix my code. Thank you for kind answer.

**Comment by nunoblue** [comment]
@mzohaibqc I fixed it and it works well. Thanks!!!
