### ISSUE TITLE
Component style issues

### ISSUE THREAD

**Issue by chenshuai2144** [mzohaibqc/antd-theme-webpack-plugin#2]
My [project](https://github.com/ant-design/ant-design-pro) have a problem.
I use your plugin, but he can only change the style of antd.
Can't change my own component.
Are you willing to help?
this is my config.
```
  const options = {
    antDir: path.join(__dirname, './node_modules/antd'),
    stylesDir: path.join(__dirname, './src/'),
    varFile: path.join(__dirname, './node_modules/antd/lib/style/themes/default.less'),
    mainLessFile: path.join(__dirname, './src/index.less'),
    themeVariables: ['@primary-color'],
    indexFileName: 'index.html',
  };
```
> Thank you anyway

**Comment by mzohaibqc** [comment]
@chenshuai2144 Sure, I will reach you around 11pm GTM + 5.

**Comment by mzohaibqc** [comment]
@chenshuai2144 Are you using `antd-tools` for build process or simple webpack?

**Comment by mzohaibqc** [comment]
Can you push your local changes for theming to remote branch so I can clone them and see what's wrong

**Comment by chenshuai2144** [comment]
I use roadhog.
I think it may be because css-module.

**Comment by mzohaibqc** [comment]
@chenshuai2144 I ran your code locally so can you specifically tell me what is the issue. Which component do you expect to change color but it's not changing. 

Few things to clear,
In order to use this plugin, all less files should be imported in main less file like this and you need to specify which colors you want to update. Currently you are updating only `@primary-color`
```

@import './components/ActiveChart/index.less';
@import './components/Charts/ChartCard/index.less';
@import './components/Charts/Field/index.less';
@import './components/Charts/MiniProgress/index.less';
@import './components/Charts/Pie/index.less';
@import './components/Charts/Radar/index.less';
...
...
```
Have a look at this diff https://github.com/ant-design/ant-design-pro/compare/v2...mzohaibqc:theme?expand=1

**Comment by chenshuai2144** [comment]
Is this a good method for components that need to be released separately?

**Comment by mzohaibqc** [comment]
@chenshuai2144 Do you have a google account so we can communicate on Hangout or chat?

**Comment by chenshuai2144** [comment]
chenshuai064@gmail.com

**Comment by chenshuai2144** [comment]
I solved this problem, but css-moudle made me feel

**Comment by mzohaibqc** [comment]
@chenshuai2144 Can you share your findings and solution with me.

**Comment by chenshuai2144** [comment]
I want to add a tool that handles css-moudle.
what should I do?

**Comment by mzohaibqc** [comment]
@chenshuai2144 Which tool and how it will affect? I am at leave and don't have my laptop with me so I'll look into this after June 20.

**Comment by chenshuai2144** [comment]
look this https://github.com/ant-design/ant-design-pro/pull/1662

**Comment by chenshuai2144** [comment]
i need a api  getLocalIdent.
Functions similar to css-moudle getLocalIdent

**Comment by mzohaibqc** [comment]
@chenshuai2144 Did it work after this change https://github.com/ant-design/ant-design-pro/pull/1662/commits/8e4e7d7aeaaf6d0060fa2ebd0959240034dc4bb1 ?

**Comment by chenshuai2144** [comment]
no ,Because css-module。
I need getLocalIdent to customize the class name

**Comment by mzohaibqc** [comment]
@chenshuai2144 I don't know what is `getLocalIdent` but if there is something that I can change to make it work, let me know

**Comment by chenshuai2144** [comment]
```
 getLocalIdent: (context, localIdentName, localName) => {
      if (context.resourcePath.includes('node_modules')) {
        return localName;
      }

      let antdProPath = context.resourcePath.match(/src(.*)/)[1].replace('.less', '');
      if (context.resourcePath.includes('components')) {
        antdProPath = antdProPath.replace('components/', '');
      }
      const arr = antdProPath
        .split('/')
        .map(a => a.replace(/([A-Z])/g, '-$1'))
        .map(a => a.toLowerCase());
      return `antd-pro${arr.join('-')}-${localName}`.replace('--', '-');
    },
```

**Comment by chenshuai2144** [comment]
I hope that you can use this method to change the css classname before converting less.

**Comment by chenshuai2144** [comment]
in base.less
```
.main {
  width: 100%;
  height: 100%;
  min-height: 100%;
  transition: 0.3s;
  &.wide {
    max-width: 1200px;
    margin: 0 auto;
  }
}

```
change to 
```
{
.antd-pro-base-main {
  width: 100%;
  height: 100%;
  min-height: 100%;
  transition: 0.3s;
  &.antd-pro-base-wide {
    max-width: 1200px;
    margin: 0 auto;
  }
}
}
```

**Comment by mzohaibqc** [comment]
@chenshuai2144 thank you so much for sharing this. I will look into this and will add in new release..

**Comment by chenshuai2144** [comment]
I have solved
