### ISSUE TITLE
Tapable.apply is deprecated. Call apply on the plugin directly instead

### ISSUE THREAD

**Issue by zomars** [mzohaibqc/antd-theme-webpack-plugin#27]
According to [this issue](https://github.com/webpack/webpack/issues/6568). We are getting this warning when trying to use this plugin with webpack 4.3.

**Comment by mzohaibqc** [comment]
@zomars I'll update my plugin soon. It is warning and not an error so if you can go with this warning, go for it otherwise wait for me to update this plugin

**Comment by mzohaibqc** [comment]
@zomars I updated the plugin and now you will see such warning. Close the issue if your issue has been resolved after testing new version.

Install `antd-theme-webpack-plugin@1.3.0`

**Comment by zomars** [comment]
Thanks, I'll test it an report ASAP 🙏

**Comment by zomars** [comment]
The warning is gone. Thank you again! I'll close the issue now.
