### ISSUE TITLE
I cant find the version 1.1.5

### ISSUE THREAD

**Issue by gebilaoman** [mzohaibqc/antd-theme-webpack-plugin#3]
I can't find the version 1.1.5 from npm or yarn.
I need u help.
```script
$ npm i antd-theme-webpack-plugin@latest  --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for antd-theme-webpack-plugin@^1.1.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

````
I find all versions on npm:
```script
$ npm view  antd-theme-webpack-plugin versions

[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.0.5',
  '1.0.6',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.1.0',
  '1.1.1',
  '1.1.2' ]
````

**Comment by mzohaibqc** [comment]
Here is what I got from this command
```
$ npm view  antd-theme-webpack-plugin versions
[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.0.5',
  '1.0.6',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.1.3',
  '1.1.4',
  '1.1.5' ]
```

**Comment by gebilaoman** [comment]
I don't know why, but I'm using version 1.2 now
![image](https://user-images.githubusercontent.com/26354664/41101997-51eb4ba8-6a98-11e8-9a52-397889a69cf1.png)

**Comment by mzohaibqc** [comment]
There are many bug fixes in latest build, you need to install that version. Have you tried `npm install antd-theme-webpack-plugin@v1.1.5` ?

**Comment by gebilaoman** [comment]
Yeah, I tried. It's a really strange question. Fortunately, I wrote the code with 1.1.2 and it worked.

**Comment by mzohaibqc** [comment]
It worked for me. 
![screen shot 2018-06-08 at 5 20 35 pm](https://user-images.githubusercontent.com/13637803/41158692-553b07a2-6b43-11e8-82c8-3b0051ba2b5f.png)
