### ISSUE TITLE
SyntaxError: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by himadrinath** [mzohaibqc/antd-theme-webpack-plugin#31]
@mzohaibqc  `SyntaxError: Inline JavaScript is not enabled. Is it set in your options?
in color.less on line 122, column 1:

121// https://github.com/ant-design/ant-motion/issues/44
122.bezierEasingMixin();
123`

why getting this?

in browser

`callExtract: undefined
callLine: NaN
column: 0
extract: (3) ["// https://github.com/ant-design/ant-motion/issues/44", ".bezierEasingMixin();", ""]
filename: "http://localhost:3000/color.less"
href: "http://localhost:3000/color.less"
index: 4144
line: 122
message: "Inline JavaScript is not enabled. Is it set in your options?"
stack: undefined
type: "Syntax"`

**Comment by himadrinath** [comment]
@its working now 

![dark_mode](https://user-images.githubusercontent.com/12247490/63787439-7240ff00-c911-11e9-8ba3-29f409adf485.gif)

before i tried with "//cdnjs.cloudflare.com/ajax/libs/less.js/3.9.0/less.min.js" now with 
"https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js" its working

**Comment by mzohaibqc** [comment]
@himadrinath Have you read the documentation? It is heading in a short README.md file. 
https://github.com/mzohaibqc/antd-theme-webpack-plugin#enable-javascript-for-less-loader

**Comment by himadrinath** [comment]
@mzohaibqc  i fixed it the problem happen when i used 
"https://cdnjs.cloudflare.com/ajax/libs/less.js/3.9.0/less.min.js"
change it to
"https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"

and the problem gone.  is their bug in 3.9.0 version

![dark_mode](https://user-images.githubusercontent.com/12247490/63826577-52472500-c97d-11e9-9cd1-319c145e7147.gif)

**Comment by himadrinath** [comment]
also npm less 3.10.3 is working

**Comment by mzohaibqc** [comment]
@himadrinath Awesome. like this repo and share with others. :)

**Comment by himadrinath** [comment]
@mzohaibqc seeing some performance problem during chrome Dev audit. Performance reduction 50%

**Comment by mzohaibqc** [comment]
there are two reasons
- less.js cdn and it's huge
- we are blocking rendering since we don't want users to see the theme transition from default to what we have selected and save in local storage or at some backend.

**Comment by himadrinath** [comment]
@mzohaibqc i  am not using cdn and also didn't see any render blocking in Dev aduit. On the very first load of the page it print and then page goes blank and after that the page print again. And also I didn't save less into my local store.
