### ISSUE TITLE
after refresh，how can the app use new setting theme?

### ISSUE THREAD

**Issue by krypton100** [mzohaibqc/antd-theme-webpack-plugin#32]
I use react app and config-overrides.js, after refresh，theme go back default,  how can the app use new setting theme?

**Comment by krypton100** [comment]
use local storage

**Comment by HaoAurora** [comment]
meet the same quesition. Can i know how to resolve it?

**Comment by mzohaibqc** [comment]
Use localstorage to save updated variables and on reload, get those
variables from localstorage and apply using modifyVars, to restore theme.

**Comment by HaoAurora** [comment]
thanks!
