### ISSUE TITLE
variable @component-background3cf is undefined

### ISSUE THREAD

**Issue by liuzhuonan** [mzohaibqc/antd-theme-webpack-plugin#4]
When I use variable primary-color, it did work. But I add  variable @component-background into the themeVariables, it doesn't work and it reported this error. Why is it so？

**Comment by liuzhuonan** [comment]
![image](https://user-images.githubusercontent.com/23043832/41085849-b61df626-6a6a-11e8-92ff-6d0492a06a62.png)
This is the Screenshots

**Comment by mzohaibqc** [comment]
@liuzhuonan Can you show more details like what's the value of this color, have you defined this color variable in `variables.less` file? Some more details

**Comment by liuzhuonan** [comment]
Yes,I carefully checked every step and it is correct. I found that if I use the variable which default value is #fff, this error will appear.Such as @component-background, @input-bg, other variable is OK.I thought may be the plugin ant-theme-generator have a bug?And If I change the defalut value in varFile,like this
![image](https://user-images.githubusercontent.com/23043832/41188953-5e3c1f60-6bf9-11e8-88cf-4857368f1706.png)
The error will not appear. But the effective value is not the value I set.See the picture.
![image](https://user-images.githubusercontent.com/23043832/41188974-984ee264-6bf9-11e8-87e6-90905a0483be.png)
![image](https://user-images.githubusercontent.com/23043832/41188985-bc4e6ebe-6bf9-11e8-9aed-f020109550a2.png)

**Comment by mzohaibqc** [comment]
@liuzhuonan you are right. In case of #fff or #000 it will not work asnd it is intentionasl becasuse doing so will replace all #fff or #000 with your varialbe name causing unwanted colors when rendered. So in order  get best out of it, use unique six character hex color codes. The whole idea is to replace matching colors with respective variables.

**Comment by liuzhuonan** [comment]
Another problem like this:
@bg-color: #ffffff;
@com-color: #ffffff;
.a {background: @bg-color};
.b {background: @com-color};
When I change @bg-color,because of the same initial value, .a and .b all changed.This is not what I want.
Is there any solution?

**Comment by mzohaibqc** [comment]
@liuzhuonan As I told you earlier, white and black don't work well. It will using pure white or black color `#fff` or `#ffffff` will break styles repalcing many other white colors with your variable. You can use some other color as default value and if still want white use `#fffffe` or something like that. Same goes for black.

**Comment by mzohaibqc** [comment]
@liuzhuonan I hope above tip fixed your issue :) closing this
