### ISSUE TITLE
background-image 的地址被覆盖

### ISSUE THREAD

**Issue by jokingzhang** [mzohaibqc/antd-theme-webpack-plugin#40]
[demo地址](https://github.com/jokingzhang/antd-theme-demo)

### 问题描述

在less文件中，同时使用 `background-image` 和 `background-color` 属性，在 `background-image` 中使用 `antd` 变量，`background-image` 的地址被改写。

### 插件配置

```js
const path = require('path');
const {
  override,
  fixBabelImports,
  addLessLoader,
  addBabelPlugins,
  addWebpackPlugin,
} = require('customize-cra');
const AntDesignThemePlugin = require('antd-theme-webpack-plugin');

const options = {
  antDir: path.join(__dirname, './node_modules/antd'),
  stylesDir: path.join(__dirname, './src'),
  varFile: path.join(__dirname, './src/variables.less'),
  mainLessFile: path.join(__dirname, './src/style.less'),
  themeVariables: ['@primary-color'],
  indexFileName: 'index.html',
  generateOnce: false, // generate color.less on each compilation
};

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addLessLoader({
    // modifyVars: {
    //   '@primary-color': '#00375B',
    // },
    javascriptEnabled: true,
  }),
  addWebpackPlugin(new AntDesignThemePlugin(options)),
);

```

### 问题截图

![clipboard_image_1586405142388](https://user-images.githubusercontent.com/10766546/78874871-a4a60380-7a7f-11ea-9400-9546e07cd43e.png)
![clipboard_image_1586405132852](https://user-images.githubusercontent.com/10766546/78874878-a66fc700-7a7f-11ea-88b5-6628581c7b7d.png)

### 期望结果
![image](https://user-images.githubusercontent.com/10766546/78875195-1aaa6a80-7a80-11ea-95eb-4365d6d1e669.png)

### 实际结果
![image](https://user-images.githubusercontent.com/10766546/78875050-e33bbe00-7a7f-11ea-9365-f7191acf9720.png)

**Comment by mzohaibqc** [comment]
@jokingzhang This issue has been fixed now. Use the latest version which is `antd-theme-webpack-plugin@1.3.2` at the time of writing this.
