### ISSUE TITLE
无法修改 node_modules 中其他使用 Antd 变量组件的 theme

### ISSUE THREAD

**Issue by jokingzhang** [mzohaibqc/antd-theme-webpack-plugin#41]
### 问题描述

我在项目，通过npm的方式，使用了一个基于Antd变量的组件。
如果 `node_modules` 中的其他组件使用了Antd的变量，那么当调用 `window.less.modifyVars(vars)` 修改变量之后，`node_modules` 中组件的样式不会生效。

### 示例地址

- [演示项目：antd-theme-demo](https://github.com/jokingzhang/antd-theme-demo)
- [单个组件地址：antd-v3-simple-switch](https://github.com/jokingzhang/antd-v3-simple-switch)

### 插件配置

```js
const path = require('path');
const {
  override,
  fixBabelImports,
  addLessLoader,
  addBabelPlugins,
  addWebpackPlugin,
} = require('customize-cra');
const AntDesignThemePlugin = require('antd-theme-webpack-plugin');

const options = {
  antDir: path.join(__dirname, './node_modules/antd'),
  stylesDir: path.join(__dirname, './src'),
  varFile: path.join(__dirname, './src/variables.less'),
  mainLessFile: path.join(__dirname, './src/style.less'),
  themeVariables: ['@primary-color'],
  indexFileName: 'index.html',
  generateOnce: false, // generate color.less on each compilation
};

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addLessLoader({
    // modifyVars: {
    //   '@primary-color': '#00375B',
    // },
    javascriptEnabled: true,
  }),
  addWebpackPlugin(new AntDesignThemePlugin(options)),
);
```
### 问题截图
运行项目，打开 http://localhost:3066/comp/switch ，可以看到示例效果：
![image](https://user-images.githubusercontent.com/10766546/78905579-ce2b5300-7ab0-11ea-9d38-7f9049f0dbba.png)

**Comment by mzohaibqc** [comment]
This is because you have not imported antd less styles in your main styles.less file

do this at the top of your styles.less or which ever is the main less file

```
@import '../../node_modules/antd/lib/style/themes/default.less';
```

**Comment by jokingzhang** [comment]
It's not work.

**Comment by jokingzhang** [comment]
我在 `mainLessFile` 文件中，引入了第三方库的less文件，问题解决了

**Comment by huxiany** [comment]
> 我在 `mainLessFile` 文件中，引入了第三方库的less文件，问题解决了

可以分享一下解决方案吗？

**Comment by jokingzhang** [comment]
> > 我在 `mainLessFile` 文件中，引入了第三方库的less文件，问题解决了
> 
> 可以分享一下解决方案吗？

`mainLessFile` 这个less文件中，只要引入所有需要改变变量的less文件即可
包含antd，以及三方库的。

**Comment by huxiany** [comment]
> > > 我在 `mainLessFile` 文件中，引入了第三方库的less文件，问题解决了
> > 
> > 
> > 可以分享一下解决方案吗？
> 
> `mainLessFile` 这个less文件中，只要引入所有需要改变变量的less文件即可
> 包含antd，以及三方库的。

好的，谢谢你的分享！

**Comment by mzohaibqc** [comment]
@huxiany I don't understand chinees and hence most of the world so kindly describe your issue in English language

**Comment by mzohaibqc** [comment]
@huxiany @jokingzhang I've fixed two bugs related to background-image and background with value as `url(some url)` that might help
`antd-theme-webpack-plugin@1.3.3`

**Comment by jokingzhang** [comment]
> @huxiany I don't understand chinees and hence most of the world so kindly describe your issue in English language

I'll be careful to use English later. Thank you for solving the problem.

**Comment by mzohaibqc** [comment]
> > @huxiany I don't understand chinees and hence most of the world so kindly describe your issue in English language
> 
> I'll be careful to use English later. Thank you for solving the problem.

So your issue has been fixed by using updated version?

**Comment by hanalice** [comment]
@jokingzhang what's the meaning of your solution?

**Comment by jokingzhang** [comment]
> > > @huxiany I don't understand chinees and hence most of the world so kindly describe your issue in English language
> > 
> > 
> > I'll be careful to use English later. Thank you for solving the problem.
> 
> So your issue has been fixed by using updated version?

Yes, problem solved.

**Comment by jokingzhang** [comment]
> @jokingzhang what's the meaning of your solution?

update to `antd-theme-webpack-plugin@1.3.3`

**Comment by hanalice** [comment]
> > @jokingzhang what's the meaning of your solution?
> 
> update to `antd-theme-webpack-plugin@1.3.3`

thanks for your response，I will try later.
