### ISSUE TITLE
why can't I set @font-size-base to customize the font-size.

### ISSUE THREAD

**Issue by hanalice** [mzohaibqc/antd-theme-webpack-plugin#42]
// vue.config.js
confireWebpack: {
plugins: [new AntDesignTHemePlugin({
            antDir: path.join(__dirname, './node_modules/ant-design-vue'),
            stylesDir: path.join(__dirname, './src/assets/theme'),
            varFile: path.join(__dirname, './src/assets/theme/variables.less'),
            mainLessFile: path.join(__dirname, './src/assets/theme/index.less'),
            outputFilePath: path.join(__dirname, './public/color.less'),
            themeVariables: ['@primary-color', '@text-color', '@font-size-base', '@font-size-lg'],
            indexFileName: './public/index.html',
            generateOnce: false,
        })]
}

// .vue 
window.less.modifyVars({
  "@primary-color": '#f5222d',
  "@text-color": '#ffb3b3',
  "@font-size-base": '12px'
});

primary-colr and text-color can change successfully. but font-size-color throw error:
![image](https://user-images.githubusercontent.com/18046501/80175982-d2677c80-8629-11ea-82f5-a7f38eea0709.png)

**Comment by mzohaibqc** [comment]
@hanalice Have you read the docs? 
```
This webpack plugin is to generate color specific less/css and inject into your index.html file so that you can change Ant Design specific color theme in browser.
```
