### ISSUE TITLE
How to switch between dark and light mode?

### ISSUE THREAD

**Issue by rszemplinski** [mzohaibqc/antd-theme-webpack-plugin#44]
Hi,

New to this whole themeing thing. I want to dynamically change colors but also be able to use the new Ant Design Dark mode whenever a user wants to. How would I do this with your system?

Here is my current `config-override.js` file:

```js
const path = require("path");
const fs = require("fs");
const {
  override,
  fixBabelImports,
  addLessLoader,
  addWebpackPlugin,
} = require("customize-cra");
const { getThemeVariables } = require("antd/dist/theme");
const AntDesignThemePlugin = require("antd-theme-webpack-plugin");

const options = {
  stylesDir: path.join(__dirname, "./src/styles"),
  antDir: path.join(__dirname, "./node_modules/antd"),
  varFile: path.join(__dirname, "./src/styles/variables.less"),
  mainLessFile: path.join(__dirname, "./src/styles/main.less"),
  themeVariables: [
    "@primary-color",
    "@secondary-color",
    "@text-color",
    "@text-color-secondary",
    "@heading-color",
    "@layout-body-background",
    "@btn-primary-bg",
    "@layout-header-background",
    "@border-color-base",
  ],
  generateOnce: true, // generate color.less on each compilation
};

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true,
  }),
  addWebpackPlugin(new AntDesignThemePlugin(options)),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: getThemeVariables({
      dark: true,
    }),
  })
);
```

**Comment by vreddy448** [comment]
i am searching for the same. not able to achieve. Can someone please suggest a way to proceed on this theme switch

**Comment by mzohaibqc** [comment]
@rszemplinski @vreddy448 Let me check how you can achieve this.

**Comment by rszemplinski** [comment]
@mzohaibqc extremely appreciate that!

**Comment by mzohaibqc** [comment]
@rszemplinski @vreddy448 I'm in process of creating a sample project using this plugin. In the meanwhile, you can have a look at how I implemented this using base script for this plugin i.e. `antd-theme-generator@1.2.2`

Here is demo project
https://github.com/mzohaibqc/antd-theme-generator/tree/master/examples/customize-cra

I've updated the plugin and you can use updated version which is `antd-theme-webpack-plugin@1.3.4` as of now.

I'll add sample code soon

**Comment by rszemplinski** [comment]
Not to pester, but will you be posting that sample code sometime soon? @mzohaibqc

**Comment by mzohaibqc** [comment]
@rszemplinski It is ready, I'll post soon

**Comment by mzohaibqc** [comment]
@rszemplinski @vreddy448 Here is a demo 
https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html

And here is code for this demo
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/customize-cra

# Note: you don't necessarily need `customize-cra` package to achieve this. Anything to inject this plugin in webpack configurations.

**Comment by mzohaibqc** [comment]
Let me know if you still have issues implementing this

**Comment by rszemplinski** [comment]
@mzohaibqc thank you so much for doing all of this. I won't be able to work on this right away but will let you know if something comes up when I do begin to work on it.

One quick question though, with that new `customize-cra` project, what generates the `color.less` file since your `package.json` `start` command doesn't run that `color.js` file anymore. Is it something you just run once and then you are done with it?

**Comment by mzohaibqc** [comment]
Ok, one thing to understand, one you are using `antd-theme-generator` package which is core script for this `antd-theme-webpack-plugin`, then you need to create a `color.js` or whatever you want to name it which when executed will produce `color.less` which you need to put in public or some directory and access it in index.html file. But when you use this webpack plugin, it does everything for you, you don't need to put color.less in index.html, you don't need to run color.js like `node color.js`. You just need to add this plugin in your webpack configurations.

**Comment by rszemplinski** [comment]
So based off what you just said, in the customize-cra project that you used as an example, should you even have the `color.js` file and `index.html` file with the `color.less` header in there?

**Comment by mzohaibqc** [comment]
I first implemented this using base script and then copied the same project and added required changes. You can remove color.js and lessjs import in index.html file

**Comment by rszemplinski** [comment]
Awesome, this should be easy enough to implement based off what I've seen. Thanks again for doing this!
