### ISSUE TITLE
can't yarn serve

### ISSUE THREAD

**Issue by Clrs-D** [mzohaibqc/antd-theme-webpack-plugin#45]
项目卡在 95% emitting AntDesignThemePlugin ，启不起来，而且装完 antd-theme-webpack-plugin 依赖后，导致 vue-i18n 用不了，请问有遇到过类似问题吗

**Comment by mzohaibqc** [comment]
I don't understand Chinees, kindly describe your issue in English

**Comment by mzohaibqc** [comment]
@Clrs-D Kindly share your code, plugin configurations, and some details about your issue.
