### ISSUE TITLE
Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by lichnow** [mzohaibqc/antd-theme-webpack-plugin#46]
已经`javascriptEnabled: true`了，可还是出现`Inline JavaScript is not enabled. Is it set in your options?`这样的错误，无法识别`color.less`中的js函数是什么原因呢？（用less v2版本没问题）
如果不用动态主题，只是自定义antd，是正常的
loader
```
if (config.antd.enabled || config.theme.enabled) {
            const varsPath = path.join(
                config.paths.src,
                config.antd.options.dir,
                config.antd.options.varFile,
            );
            if (!isFile(varsPath)) {
                throw new Error(`Style variables path ${varsPath} not exists!`);
            }
            const customModifyVars = getThemeVariables(
                fs.readFileSync(varsPath, 'utf8'),
            );
            lessOptions = {
                ...lessOptions,
                javascriptEnabled: true,
                modifyVars: {
                    ...lessOptions.modifyVars,
                    ...customModifyVars,
                },
            };
        }
        rules.use('less').loader('less-loader').options({
            sourceMap: config.isdev,
            lessOptions,
        });
```
插件
```
chain.when(config.theme.enabled, (chainPipe) => {
        chainPipe
            .plugin('theme')
            .use(new AntDesignThemePlugin(getThemeOptions(config)))
            .end()
            .plugin('copy')
            .use(new CopyPlugin(getCopyLessPatterns(config)))
            .end();
```
`getThemeOptions(config)`生成的配置
```
antDir: '/xxx/admin/node_modules/antd',
  stylesDir: '/xxx/admin/apps/admin/src/styles',
  varFile: '/xxx/admin/apps/admin/src/styles/variables.less',
  mainLessFile: '/xxx/admin/apps/admin/src/styles/main.less',
  themeVariables: [
    '@primary-color',
   ...
  ],
  indexFileName: 'index.html',
  generateOnce: false,
  lessUrl: '/less.min.js',
  publicPath: '',
```
在devmiddlware下运行 `less.min.js`以及`color.less`都能正常访问，就是`color.less`出现`Inline JavaScript is not enabled`这样的错误

**Comment by mzohaibqc** [comment]
Seems like your issue with your less-loader configurations

**Comment by lichnow** [comment]
@mzohaibqc  href less file can not work on less 3.x version(my less-loader config is right),so I install `@type/less`,and use like
``
useEffect(() => {
        less.modifyVars(current.vars)
            .then(() => saveLocalTheme(current.name))
            .catch((error: any) => {
                console.log(error);
                message.error(`Failed to change theme`);
            });
    }, [current.name]);
    useEffect(() => {
        less.modifyVars(current.vars)
            .then(() => {
                if (enabledColor) saveLocalVars(themes);
            })
            .catch((error: any) => {
                console.log(error);
                message.error(`Modify theme vars failed`);
            });
    }, [themes]);`
```
Now work fine

**Comment by mzohaibqc** [comment]
Can you create a sample project and reproduce this issue. I'll look into that.
First thing, try `less@2.7.2` which you are importing in `index.html` file or use this cdn url which I am using in different examples `https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js`

**Comment by lichnow** [comment]
@mzohaibqc my less version is **3.x**,so it can't work fine.how to let `/color.less` work in 3.x,so  `/color.less` can work with the less.js which of less-loader's used(I config the webpack copy plugin let /node_modules/less/dist/less.min.js auto copy to dist/public dir)?

**Comment by mzohaibqc** [comment]
I think, there is an issue with using less3.x with ant design specific less styles and function so I would say, start using less@2.7.2 a CDN or simply download that file in your public folder and import from there. I'll update if there will any progress on this issue.
