### ISSUE TITLE
changing non color variables dynamically

### ISSUE THREAD

**Issue by NicoP-tickitto** [mzohaibqc/antd-theme-webpack-plugin#47]
Hi, 
So I am trying to create a new theme that can be changed at runtime. I believe I have it working as I am able to change @primary-color at runtime, so that is all good. Although I can not change other variables such as @card-radius. 

Does this library only support color variables? Is there a way around this?

How I am changing the variables:

`    window.less.modifyVars({ '@primary-color': 'green', '@card-radius': '1rem' })`

**Comment by mzohaibqc** [comment]
This is not in the scope of this plugin. This is just for color related variables and adding logic for other type of variables can be possible but I don't have time to do that. Any PRs are most welcome.
