### ISSUE TITLE
Create React App Example not working

### ISSUE THREAD

**Issue by rayvikram** [mzohaibqc/antd-theme-webpack-plugin#63]
**Describe the bug**
Example in create react app is not working with npm or yarn.

**Show your code**
No code changes done 

**Screenshots**
`callExtract: undefined
callLine: NaN
column: 32
extract: Array(3)
0: "@link-color             : @primary-color;"
1: "@link-hover-color       : color(~`colorPalette("@{link-color}", 5)`);"
2: "@link-active-color      : color(~`colorPalette("@{link-color}", 7)`);"
length: 3
__proto__: Array(0)
filename: "http://localhost:3000/color.less"
href: "http://localhost:3000/color.less"
index: 141741
line: 1567
message: "variable @link-color is undefined"
stack: undefined
type: "Name"
__proto__: Error`

**Version**

I saw that You have updated the customize-cra example 4 months back. Can you please look into create-react-app ? or at least point the changes that I need to do.

**Comment by mzohaibqc** [comment]
Do you need create-react-app example or example using `react-app-rewired` ? Since `customize-cra` example is actually a create-react-project and customize-cra is being used to overridde webpack config. I recommend using that example since that is upto date and will be maintained in future.

**Comment by rayvikram** [comment]
Yes I tried `customize-cra` it is working. Thanks for it.

**Comment by rayvikram** [comment]
Yes I tried customize-cra it is working. Thanks for it.

**Comment by rayvikram** [comment]
Yes I tried customize-cra it is working. Thanks for it.

**Comment by mzohaibqc** [comment]
@rayvikram good to hear that
