### ISSUE TITLE
craco introduction of ‘antd-theme-webpack-plugin’ has no effect

### ISSUE THREAD

**Issue by XuJin186** [mzohaibqc/antd-theme-webpack-plugin#70]
**Describe the bug**
Craco's introduction of ‘antd-theme-webpack-plugin’ has no effect
**Show your code**
`const path = require("path");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");

const AntdDayjsWebpackPlugin = require("antd-dayjs-webpack-plugin");
const ProgressBarPlugin = require("progress-bar-webpack-plugin");
const AntDesignPlugin = require("craco-antd");
const getCSSModuleLocalIdent = require("react-dev-utils/getCSSModuleLocalIdent");
const AntDesignThemePlugin = require("antd-theme-webpack-plugin");
const lessToJs = require("less-vars-to-js");
const fs = require("fs");
const webPackConfig = {
  babel: {
    plugins: [
      [
        "import",
        {
          libraryName: "lodash",
          camel2DashComponentName: false,
          libraryDirectory: "",
        },
        "lodash",
      ],
      ["@babel/plugin-syntax-dynamic-import"],
    ],
  },
  plugins: [
    {
      plugin: AntDesignPlugin,
      options: {
        cssLoaderOptions: {
          modules: {
            getLocalIdent: (context, localIdentName, localName, options) => {
              if (context.resourcePath.includes("node_modules")) {
                return localName;
              }
              return getCSSModuleLocalIdent(
                context,
                localIdentName,
                localName,
                options
              );
            },
          },
        },

        babelPluginImportOptions: {
          libraryDirectory: "es",
        },
      },
    },
  ],
  // 14.74
  webpack: {
    plugins: [
      new AntDesignThemePlugin({
        varFile: path.join(__dirname, "./src/styles/variables.less"),
        mainLessFile: path.join(__dirname, "./src/styles/index.less"),
        antDir: path.join(__dirname, "./node_modules/antd"),
        stylesDir: path.join(__dirname, "./src/styles"),
        themeVariables: Object.keys(
          lessToJs(
            fs.readFileSync(
              path.join(
                __dirname,
                "./node_modules/antd/lib/style/themes/default.less"
              ),
              "utf8"
            )
          )
        ),
        // indexFileName: 'index.html',
        generateOnce: true,
      }),

      new ProgressBarPlugin(),
      ...(process.env.NODE_ENV === "development"
        ? [new BundleAnalyzerPlugin({ openAnalyzer: false })]
        : []),

      new AntdDayjsWebpackPlugin(),
    ],
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@components": path.resolve(__dirname, "./src/components"),
      "@utils": path.resolve(__dirname, "./src/utils"),
      "@views": path.resolve(__dirname, "./src/views"),
      "@assets": path.resolve(__dirname, "./src/assets"),
      "@layouts": path.resolve(__dirname, "./src/layouts"),
      "@config": path.resolve(__dirname, "./src/config"),
      "@constants": path.resolve(__dirname, "./src/constants"),
      "@services": path.resolve(__dirname, "./src/services"),
      "@store": path.resolve(__dirname, "./src/store"),
      "@hooks": path.resolve(__dirname, "./src/hooks"),
      "@models": path.resolve(__dirname, "./src/models"),
      "@decorators": path.resolve(__dirname, "./src/decorators"),
    },
  },
};

module.exports = webPackConfig;
`

**Screenshots**

**Version**
   "antd-theme-webpack-plugin": "^1.3.6",

Hope to provide craco case. Thank you very much

**Comment by mzohaibqc** [comment]
Seems like you are using css-modules which is not supported yet.

**Comment by XuJin186** [comment]
Through debugging, it was found that the index.html file was not found. In fact, the html plug-in of webpack has not been called. Just change the order of the plug-ins.
