### ISSUE TITLE
addAssets = (compilation, assets, callback), SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by zhouccccc** [mzohaibqc/antd-theme-webpack-plugin#80]
**Describe the bug**
My FE project is based on umi.js, recently my team want build project on the cloud but found this problem, But when I changed the plugin version to 1.3.7, everything run well 

**Show your code**
`config.plugin('ant-design-theme').use(AntDesignThemePlugin, [
      {
        antDir: path.join(__dirname, '../node_modules/antd'),
        stylesDir,
        varFile: path.join(__dirname, '../node_modules/antd/lib/style/themes/default.less'),
        mainLessFile: outFile, //     themeVariables: ['@primary-color'],
        indexFileName: 'index.html',
        generateOne: true,
        lessUrl: 'https://gw.alipayobjects.com/os/lib/less.js/3.8.1/less.min.js',
      },
    ]);`

**Screenshots**
![image](https://user-images.githubusercontent.com/25141787/107168220-ff88ee00-69f5-11eb-8114-b803e5966535.png)

**Version**
FE Project
- umi  ^2.9.0

Deploy Plateform
- Node v10.6.0
- NPM v6.1.0

**Comment by zhouccccc** [comment]
BTW. Build job on the mac is OK

**Comment by rimwoorim** [comment]
我也是遇到同样的问题

**Comment by zhouccccc** [comment]
> 我也是遇到同样的问题
You can change the plugin version to 1.3.7
I think it will works!

**Comment by mzohaibqc** [comment]
@JoeCMorgan New changes (arrow functions as class methods) are causing this issue. Can you kindly fix this? I can do that but I'm not sure whether it will break code or not due to `this` keyword.

**Comment by mzohaibqc** [comment]
@rimwoorim @zhouccccc Kindly use previous version i.e. v1.3.7 untill this problem is fixed. There is no functionality difference in both versions. v1.3.8 added support for webpack@5 so you can safely install previous version.

**Comment by zhouccccc** [comment]
@mzohaibqc Thanks for your reply. The previous version 1.3.7 works normally, I had changed it !

**Comment by JoeCMorgan** [comment]
That's odd. I'll take a look this morning and replace the arrow functions with standard functions 👍🏼

**Comment by mzohaibqc** [comment]
@zhouccccc @rimwoorim Kindly try new version i.e. v1.3.9, hopefully it will resolve this issue.

**Comment by zhouccccc** [comment]
Sounds good. I will try it later. Thanks! @mzohaibqc
